name: Share data between jobs

on: [push]

jobs:
  job_1:
    name: checking directories in repo
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          ls -l
  job_2:
    name: installing python librarires
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          pip3 install matplotlib
          pip3 install pandas
          python3 ./scripts/git-actions.py
  job_3:
    name: Multiply by 9
    needs: job_1
    runs-on: windows-latest
    steps:
      - name: Download math result for job 1
        uses: actions/download-artifact@v1
        with:
          name: homework
      - shell: bash
        run: |
          value=`cat homework/math-homework.txt`
          expr $value \* 9 > homework/math-homework.txt
      - name: Upload math result for job 2
        uses: actions/upload-artifact@v1
        with:
          name: homework
          path: homework/math-homework.txt

  job_4:
    name: Display results
    needs: job_2
    runs-on: macOS-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Download math result for job 2
        uses: actions/download-artifact@v1
        with:
          name: homework
      - name: Print the final result
        shell: bash
        run: |
          value=`cat homework/math-homework.txt`
          echo The result is $value
      - name: check existance of file
        run: ls
      - name: upload artifact to repo
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: homework/math-homework.txt 
      - name: download artifact
        uses: actions/download-artifact@v2
        with:
           name: my-artifact
      - name: print confirmation status
        shell: bash
        run: |
          echo Sucess!
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "added files" || exit 0
      - name: Push Diagrams
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

